version: "3.7"

services:
  estado:
    build: ./servicoEstado
    container_name: servicoEstado
    ports:
      - 3000:3000
    volumes:
      - ./servicoEstado:/usr/app
    links:
      - populacao
    networks:
      - servicesnet

  populacao:
    build: ./servicoPopulacao
    container_name: servicoPopulacao
    ports:
      - 3001:3001
    volumes:
      - ./servicoPopulacao:/usr/app
    networks:
      - servicesnet

networks:
  servicesnet:
    driver: "bridge"